[images]
  remote_images = [
    "https://ext.same-assets.com/543785121/**",
    "https://ext.same-assets.com/1113238889/**",
    "https://i0.wp.com/demo.wpzoom.com/cookbook/files/**",
    "https://demo.wpzoom.com/cookbook/files/**"
  ]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
